// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SC_DbConfig;

#nullable disable

namespace SC_DbConfig.Migrations
{
    [DbContext(typeof(SC_DbContext))]
    [Migration("20240719084725_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SC_DbConfig.Dept", b =>
                {
                    b.Property<Guid>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AV")
                        .HasColumnType("bit");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrgOwn")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("UserOwn")
                        .HasColumnType("bigint");

                    b.HasKey("DeptId");

                    b.HasIndex("UserOwn");

                    b.ToTable("T_Depts", (string)null);
                });

            modelBuilder.Entity("SC_DbConfig.Emp", b =>
                {
                    b.Property<long>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EmpId"));

                    b.Property<bool>("AV")
                        .HasColumnType("bit");

                    b.Property<Guid>("DeptOwn")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserOwn")
                        .HasColumnType("bigint");

                    b.HasKey("EmpId");

                    b.HasIndex("UserOwn");

                    b.ToTable("T_Emps", (string)null);
                });

            modelBuilder.Entity("SC_DbConfig.Org", b =>
                {
                    b.Property<Guid>("OrgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrgName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserOwn")
                        .HasColumnType("bigint");

                    b.HasKey("OrgId");

                    b.HasIndex("UserOwn");

                    b.ToTable("T_Orgs", (string)null);
                });

            modelBuilder.Entity("SC_DbConfig.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<string>("Acct")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nick")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("pwd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("T_Users", (string)null);
                });

            modelBuilder.Entity("SC_DbConfig.Dept", b =>
                {
                    b.HasOne("SC_DbConfig.User", "FKUserOwn")
                        .WithMany("FKDepts")
                        .HasForeignKey("UserOwn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FKUserOwn");
                });

            modelBuilder.Entity("SC_DbConfig.Emp", b =>
                {
                    b.HasOne("SC_DbConfig.User", "FKUserOwn")
                        .WithMany("FKEmps")
                        .HasForeignKey("UserOwn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FKUserOwn");
                });

            modelBuilder.Entity("SC_DbConfig.Org", b =>
                {
                    b.HasOne("SC_DbConfig.User", "FKUserOwn")
                        .WithMany("FKOrgs")
                        .HasForeignKey("UserOwn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FKUserOwn");
                });

            modelBuilder.Entity("SC_DbConfig.User", b =>
                {
                    b.Navigation("FKDepts");

                    b.Navigation("FKEmps");

                    b.Navigation("FKOrgs");
                });
#pragma warning restore 612, 618
        }
    }
}
